import { defaultConfig } from './config.js';
const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),playBtn=$('#playBtn'),stepBtn=$('#stepBtn'),speedBtn=$('#speedBtn'),resetBtn=$('#resetBtn'),stepLabel=$('#stepLabel'),stats=$('#stats'),sheet=$('#sheet'),delta=$('#deltaP1'),deltaOut=$('#deltaOut');
const worker=new Worker('./src/simulation.worker.js',{type:'module'});
let W=0,H=0,dpr=1,playing=false,speed=1,selected=-1,pan={x:0,y:0},zoom=1,pointers=new Map(),lastPinch=0;
let frame={step:0,values:[],groups:[],edges:[],metrics:{means:[],variances:[],density:0}},pos=new Float32Array(defaultConfig.nodeCount*2);
function initPositions(){let s=defaultConfig.seed;const r=()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};for(let i=0;i<defaultConfig.nodeCount;i++){const g=i%3,a=r()*Math.PI*2,rr=45+g*95+r()*70;pos[i*2]=Math.cos(a)*rr;pos[i*2+1]=Math.sin(a)*rr}}
function updateStats(){const m=frame.metrics;stepLabel.textContent=`STEP ${frame.step}`;stats.innerHTML=`SEED ${defaultConfig.seed}<br>NODES ${defaultConfig.nodeCount}<br>EDGES ${frame.edges.length}<br>DENSITY ${(m.density*100).toFixed(2)}%<br>${m.means.map((v,i)=>`P${i+1} μ ${v.toFixed(3)} σ² ${m.variances[i].toFixed(3)}`).join('<br>')}`}
worker.onmessage=e=>{frame=e.data;updateStats()};worker.postMessage({type:'init',config:defaultConfig});initPositions();
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function screen(i){return[W/2+pan.x+pos[i*2]*zoom,H/2+pan.y+pos[i*2+1]*zoom]}
function render(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#07090d';ctx.fillRect(0,0,W,H);ctx.lineCap='round';for(const [a,b,s] of frame.edges){const A=screen(a),B=screen(b);ctx.strokeStyle=`rgba(225,233,247,${.018+s*.20})`;ctx.lineWidth=.3+s*.9;ctx.beginPath();ctx.moveTo(...A);ctx.lineTo(...B);ctx.stroke()}const D=defaultConfig.dimensions;for(let i=0;i<defaultConfig.nodeCount;i++){const [x,y]=screen(i),base=i*D,strength=((frame.values[base]||0)+(frame.values[base+1]||0)+(frame.values[base+2]||0))/3,r=(1.3+strength*3.5)*(i===selected?1.9:1);if(i===selected){ctx.shadowBlur=24;ctx.shadowColor='white'}ctx.fillStyle=`rgba(239,244,255,${.14+strength*.84})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}requestAnimationFrame(render)}
let acc=0,last=performance.now();function loop(t){const dt=t-last;last=t;if(playing){acc+=dt;const interval=1000/(30*speed);let n=0;while(acc>=interval&&n++<50){worker.postMessage({type:'step',count:1});acc-=interval}}requestAnimationFrame(loop)}
function pick(x,y){let best=-1,bd=18;for(let i=0;i<defaultConfig.nodeCount;i++){const p=screen(i),d=Math.hypot(p[0]-x,p[1]-y);if(d<bd){bd=d;best=i}}selected=best}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,px:e.clientX,py:e.clientY,t:performance.now()})});
canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;p.px=p.x;p.py=p.y;p.x=e.clientX;p.y=e.clientY;if(pointers.size===1){pan.x+=p.x-p.px;pan.y+=p.y-p.py}else if(pointers.size===2){const q=[...pointers.values()],d=Math.hypot(q[0].x-q[1].x,q[0].y-q[1].y);if(lastPinch)zoom=Math.max(.25,Math.min(5,zoom*d/lastPinch));lastPinch=d}});
canvas.addEventListener('pointerup',e=>{const p=pointers.get(e.pointerId);if(p&&Math.hypot(p.x-p.sx,p.y-p.sy)<8&&performance.now()-p.t<350)pick(e.clientX,e.clientY);pointers.delete(e.pointerId);if(pointers.size<2)lastPinch=0});
playBtn.onclick=()=>{playing=!playing;playBtn.textContent=playing?'❚❚':'▶'};stepBtn.onclick=()=>worker.postMessage({type:'step',count:1});speedBtn.onclick=()=>{speed=speed===1?10:speed===10?100:1;speedBtn.textContent=`×${speed}`};resetBtn.onclick=()=>{playing=false;playBtn.textContent='▶';selected=-1;pan={x:0,y:0};zoom=1;worker.postMessage({type:'reset'})};$('#interveneBtn').onclick=()=>sheet.classList.remove('hidden');$('#closeSheet').onclick=()=>sheet.classList.add('hidden');delta.oninput=()=>deltaOut.value=`${delta.value>=0?'+':''}${Number(delta.value).toFixed(2)}`;$('#applyIntervention').onclick=()=>{if(selected>=0)worker.postMessage({type:'intervene',index:selected,dimension:0,delta:Number(delta.value)});sheet.classList.add('hidden')};
addEventListener('resize',resize);resize();render();loop(performance.now());
