let cfg, step=0, values, next, groups, edges=[];let seed=1;
const rand=()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296};
const clamp=v=>Math.max(0,Math.min(1,v));
function distance(i,j){let s=0;for(let d=0;d<cfg.dimensions;d++){const q=values[i*cfg.dimensions+d]-values[j*cfg.dimensions+d];s+=q*q}return Math.sqrt(s)}
function rebuildEdges(){edges=[];for(let i=0;i<cfg.nodeCount;i++)for(let j=i+1;j<cfg.nodeCount;j++){const d=distance(i,j);if(d<cfg.rules.linkDistance&&rand()<cfg.rules.linkChance)edges.push([i,j,1-d/cfg.rules.linkDistance])}}
function init(config){cfg=config;step=0;seed=cfg.seed||1;values=new Float32Array(cfg.nodeCount*cfg.dimensions);next=new Float32Array(values.length);groups=new Uint8Array(cfg.nodeCount);let i=0;cfg.groups.forEach((g,gi)=>{for(let n=0;n<g.count&&i<cfg.nodeCount;n++,i++){groups[i]=gi;for(let d=0;d<cfg.dimensions;d++){const r=g.ranges[d]||[0,1];values[i*cfg.dimensions+d]=r[0]+rand()*(r[1]-r[0])}}});while(i<cfg.nodeCount){groups[i]=0;for(let d=0;d<cfg.dimensions;d++)values[i*cfg.dimensions+d]=rand();i++}rebuildEdges();emit('ready')}
function tick(count=1){for(let k=0;k<count;k++){for(let i=0;i<cfg.nodeCount;i++)for(let d=0;d<cfg.dimensions;d++){let sum=0,c=0;for(const e of edges){const j=e[0]===i?e[1]:e[1]===i?e[0]:-1;if(j>=0){sum+=values[j*cfg.dimensions+d];c++}}const v=values[i*cfg.dimensions+d];next[i*cfg.dimensions+d]=clamp(v+(c?(sum/c-v)*cfg.rules.convergence:0)+(rand()*2-1)*cfg.rules.noise)}values.set(next);step++;if(step%cfg.rules.rebuildEvery===0)rebuildEdges()}emit('frame')}
function metrics(){const means=Array(cfg.dimensions).fill(0),vars=Array(cfg.dimensions).fill(0);for(let i=0;i<cfg.nodeCount;i++)for(let d=0;d<cfg.dimensions;d++)means[d]+=values[i*cfg.dimensions+d]/cfg.nodeCount;for(let i=0;i<cfg.nodeCount;i++)for(let d=0;d<cfg.dimensions;d++){const q=values[i*cfg.dimensions+d]-means[d];vars[d]+=q*q/cfg.nodeCount}return {means,variances:vars,density:edges.length/(cfg.nodeCount*(cfg.nodeCount-1)/2)}}
function emit(type){postMessage({type,step,values:Array.from(values),groups:Array.from(groups),edges,metrics:metrics()})}
onmessage=e=>{const m=e.data;if(m.type==='init')init(m.config);if(m.type==='step')tick(m.count||1);if(m.type==='intervene'&&values){const {index,dimension=0,delta=0}=m;values[index*cfg.dimensions+dimension]=clamp(values[index*cfg.dimensions+dimension]+delta);rebuildEdges();emit('frame')}if(m.type==='reset')init(cfg)};
